final laConviVersace = [
  'Juntas por la noche',
  'Puestas pal derroche',
  'Tu pelo azabache',
  'La combi Versace',
  'Juntas por la noche',
  'Puestas pal derroche',
  'Tu pelo azabache',
  'La combi Versace',
  'Que fue, que fue, que fue',
  'Vestida con colabo',
  '(Margiela colabo)',
  'Medusa arriba y abajo',
  '(Carla Bruni, wah, woh)',
  'Donatella friendzy',
  '(Kilos, kilos e tela)',
  'Soltando los benjis',
  '(Cheques, cheques)',
  'Hace party con la Fania',
  'Jangueando con salseros',
  'Bendicen toda mis canciones',
  'Para que tú te enamores',
  'Juntas por la noche',
  'Puestas pal derroche',
  'Tu pelo azabache',
  'La combi Versace',
  'Juntas por la noche',
  'Puestas pal derroche',
  'Tu pelo azabache',
  'La combi Versace',
  'Rosí season coming',
  '(Expensiva)',
  'Uzi y Albinoni',
  'Facetime con Milano',
  '(Tim Cook)',
  'Dios bendiga a Gianni',
  '(Flores para Gianni)',
  'Más fría que tu baby mama',
  'Nos fuimos 7:30',
  'Llego a la Met en pony (ah)',
  'Pa que tú te enamores',
  'Juntas por la noche',
  'Puestas pal derroche',
  'Tu pelo azabache',
  'La combi Versace',
  'Juntas por la noche',
  'Puestas pal derroche',
  'Tu pelo azabache',
  'La combi Versace',
  'Este lazo Versace saliendo del callejón',
  'Desfilamos Dior custom en el colmadón',
  'Con la tanga Gucci en una cola de motor',
  'Me llevo todo el mall montao en un camión',
  'Combino el rojo con el rosa',
  'Vestida de blanco',
  'Me visto de novia pero no soy tu esposa',
  'Las tennis Valentino',
  'Bizcocho de Moschino',
  'Gargantilla de zafiro',
  'Con diamante azul marino',
  'Y si hoy llevo la ropa fake',
  'Es porque soy la más real',
  'Bish, me creo Dapper Dan',
  'Me doy un flow de paca, me veo original',
  'Soy la marca más cara que tú no va a pode capea',
  'Juntas por la noche',
  'Puestas pal derroche',
  'Tu pelo azabache',
  'La combi Versace',
  'Juntas por la noche',
  'Puestas pal derroche',
  'Tu pelo azabache',
  'La combi Versace',
  'Fue el roman-, fue el roman-',
  'Colale , fue el roman-, hmmm',
  'Se me ve el culo en Versace',
  'Fue-fuera del bajo mundo, fuera',
  'Colale, cola-, colale, mmm, mmm, mmm',
  'Fuera, fuera, fuera',
  'Fuera, fuera, fuera',
  'Ah, ah',
  'Se me ve el culo en Versace',
  'Se me ve el culo en Versace',
  'Del bajo mun-, del bajo mun-, yeh',
  'Del bajo mun-, yeh',
  'Mmm, ah, ah, mmm, cheque',
];

final saoko = [
  'Chica, ¿qué dices?',
  'Saoko, papi, saoko',
  'Saoko, papi, saoko',
  'Chica, ¿qué dices?',
  'Saoko, papi, saoko',
  'Saoko, papi, saoko',
  'Saoko, papi, saoko-ko',
  'Cuando pone perla en el collar de Vivienne',
  'E diferente, ya no son perla, uh, no',
  'Cuando los cubito de hielo ya no es agua',
  'Ahora es hielo, se congela, uh, no',
  'Cuando es de noche en el cielo',
  'Y se vuelve de día, ya to eso cambió',
  'Cuando el caballo entra a Troya',
  'Tú te confías y ardió (uh, no), uh, no',
  'Eh, yo soy muy mía, yo me transformo',
  'Una mariposa, yo me transformo',
  'Makeup de drag queen, yo me transformo',
  'Lluvia de estrella, yo me transformo',
  'Pasá de vuelta, yo mе transformo',
  'Como Sex Siren, yo me transformo',
  'Me contradigo, yo me transformo',
  'Soy toa las cosa, yo me transformo',
  'Frank me dice que abra el mundo como una nue',
  'Si me muero, que me muera por la boca como muere el pe',
  'Sé quién soy, y a donde voy ya nunca se me olvida (uh, uh, uh)',
  'Yo manejo, Dios me guía',
  'El logo de LEGO, bebé (pu-pu-pu-pu)',
  'Kim K cuando está blonde, bebé (pu-pu-pu-pu)',
  'Un tee white con tie-dye, bebé (pu-pu-pu-pu)',
  'La calle en Navidad, bebé',
  'Como un pavo real, bebé (pu-pu-pu-pu)',
  'La cerilla al quemar, bebé (pu-pu-pu-pu)',
  'Tu cara, tu mirá, bebé (pu-pu-pu-pu)',
  'Si te vuelvo a besar, bebé',
  'Mira, ja, a ver si sirven de algo, ja, ja, ja',
  'Los caramelo de la voz, a ver',
  'Si ere la pámpara, nada te pue parar, uh',
  'Si ere la pámpara, nada te pue parar, y ya',
  'Fuck el estilo',
  'Fuck el estilo',
  'Fuck el stylist',
  'Fuck el estilo',
  'Tela y tijera, y ya',
  'Cógela y córtala, y ya',
  'Cógela y córtala, y ya',
  'Cógela y córtala, y ya',
  'Cógela y córtala, y ya',
  'Cógela y córtala',
  'Cógela y córtala',
  'Cógela y córtala',
];
