final saoko = [
  'Chica, ¿qué dices?',
  'Saoko, papi, saoko',
  'Saoko, papi, saoko',
  'Chica, ¿qué dices?',
  'Saoko, papi, saoko',
  'Saoko, papi, saoko',
  'Saoko, papi, saoko-ko',
  'Cuando pone perla en el collar de Vivienne',
  'E diferente, ya no son perla, uh, no',
  'Cuando los cubito de hielo ya no es agua',
  'Ahora es hielo, se congela, uh, no',
  'Cuando es de noche en el cielo',
  'Y se vuelve de día, ya to eso cambió',
  'Cuando el caballo entra a Troya',
  'Tú te confías y ardió (uh, no), uh, no',
  'Eh, yo soy muy mía, yo me transformo',
  'Una mariposa, yo me transformo',
  'Makeup de drag queen, yo me transformo',
  'Lluvia de estrella, yo me transformo',
  'Pasá de vuelta, yo mе transformo',
  'Como Sex Siren, yo me transformo',
  'Me contradigo, yo me transformo',
  'Soy toa las cosa, yo me transformo',
  'Frank me dice que abra el mundo como una nue',
  'Si me muero, que me muera por la boca como muere el pe',
  'Sé quién soy, y a donde voy ya nunca se me olvida (uh, uh, uh)',
  'Yo manejo, Dios me guía',
  'El logo de LEGO, bebé (pu-pu-pu-pu)',
  'Kim K cuando está blonde, bebé (pu-pu-pu-pu)',
  'Un tee white con tie-dye, bebé (pu-pu-pu-pu)',
  'La calle en Navidad, bebé',
  'Como un pavo real, bebé (pu-pu-pu-pu)',
  'La cerilla al quemar, bebé (pu-pu-pu-pu)',
  'Tu cara, tu mirá, bebé (pu-pu-pu-pu)',
  'Si te vuelvo a besar, bebé',
  'Mira, ja, a ver si sirven de algo, ja, ja, ja',
  'Los caramelo de la voz, a ver',
  'Si ere la pámpara, nada te pue parar, uh',
  'Si ere la pámpara, nada te pue parar, y ya',
  'Fuck el estilo',
  'Fuck el estilo',
  'Fuck el stylist',
  'Fuck el estilo',
  'Tela y tijera, y ya',
  'Cógela y córtala, y ya',
  'Cógela y córtala, y ya',
  'Cógela y córtala, y ya',
  'Cógela y córtala, y ya',
  'Cógela y córtala',
  'Cógela y córtala',
  'Cógela y córtala',
];

final candy = [
  'Vestida con F de Fendi',
  'Bailando Plan B, la de Candy',
  'Así tú te prendaste de mí',
  'El día en que yo te conocí',
  'Sé que tú',
  'No me has olvidao',
  'No me has olvidao',
  'No me has olvidao',
  'Solo tú',
  'No me has olvidao',
  'No me has olvidao',
  'No me has olvidao',
  'Ya no te quiero como antes',
  'Me rompiste, pero solo en parte',
  'Llevaba tu esclava para pensarte',
  'Pero de olvidarte yo ya hice un arte',
  'Más na, na-na-na-na-na',
  'No queda na-na-na-na-na',
  'Entre tú y yo ya-ya-ya-ya',
  'Ya no me acuerdo de tu cara',
  'La forma de tu cuerpo ni aunque la pensara',
  'Hay demasiao que nos separa',
  'La vida es bonita, pero es traicionera',
  'Vestía con F de Fendi (Fendi, Fendi, Fendi)',
  'Bailando Plan B, la de Candy (Candy, Candy, Candy)',
  'Así tú te prendaste de mí (eh, eh)',
  'El día que yo te conocí',
  'Pero tú',
  'No me has olvidao',
  'No me has olvidao',
  'No me has olvidao',
  'Solo tú',
  'No me has olvidao',
  'No me has olvidao',
  'No me has olvidao',
  'Na-na-na-na-na',
  'No queda na-na-na-na-na',
  'Entre tú y yo ya-ya-ya-ya',
  'Na-na-na-na-na',
  'No queda na-na-na-na-na',
  'Entre tú y yo ya-ya-ya-ya',
  'Vestía con F de Fendi (Fendi, Fendi, Fendi)',
  'Bailando Plan B, la de Candy (Candy, Candy, Candy)',
  'Así tú te prendaste de mí (eh, eh)',
  'El día que yo te conocí (sí, sí)',
  'Vestía con F de Fendi (Fendi, Fendi, Fendi)',
  'Bailando Plan B, la de Candy (Candy, Candy, Candy)',
  'Así tú te prendaste de mí (eh, eh)',
  'El día que yo te conocí (sí, sí, sí)',
  'Pero tú',
  'No me has olvidao',
  'No me has olvidao',
  'No me has olvidao',
  'Solo tú',
  'No me has olvidao',
  'No me has olvidao',
  'No me has olvidao',
];

final laFama = [
  'Lo que pasó, a ti te lo cuento',
  'No creas que no dolió o que me lo invento',
  'Así es que se dio',
  'Yo tenía mi bebé, era algo bien especial',
  'Pero me obsesioné con algo que a él le hacía mal',
  'Miles de cancione en mi mente y él me lo notaba',
  'Y él tanta vece que me lo decía y yo como si nada',
  'Es mala amante la fama y no va a quererte de verdad',
  'Es demasiao traicionera, y como ella viene, se te va',
  'Sabe que será celosa, yo nunca le confiaré',
  'Si quiere duerme con ella, pero nunca la vayas a casar',
  'Lo que pasó me ha dejado en vela',
  'Ya no puedo ni pensar',
  'La sangre le hierve',
  'Siempre quiere más',
  'Puñalaitas da su ambición',
  'En el pecho, afilada, es lo peor',
  'Es mala amante la fama y no va a quererme de verdad',
  'Es demasiao traicionera y como ella viene, se me va',
  'Yo sé que será celosa, yo nunca le confiaré',
  'Si quiero duermo con ella, pero nunca me la voy a casar',
  'No hay manera',
  'De que esta obsesión se me fuera',
  'Se me fuera ya desaparezca',
  'Yo aún no he aprendio la manera',
  'No hay manera que desaparezca',
  'Es mala amante la fama y no va a quererte de verdad',
  'Es demasiao traicionera y como ella viene, se te va',
  'Yo sé que será celosa, yo nunca le confiaré',
  'Si quiero duermo con ella, pero nunca me la voy a casar',
];
final bulerias = [
  'Yo no tuve que hacer naíta que yo no quisiera',
  'Y aunque ahora nadie lo ve (dale)',
  'Yo no tuve que hacer nada que me arrepienta',
  ' ni de que yo lamente ahora',
  'Para mantenerme en pie, yo me maté 24/7',
  'Eso elo que tuve que hacer (ole)',
  'Soy igual de cantaora (dale, dale)',
  'Igual de cantaora con un chándal de Versace que vestíita de bailaora',
  'Con un chándal de Versace que vestiíta de bailaora',
  'Y aunque a mí me maldigan a mis espalda',
  'De cada puñalaíta saco mi rabia',
  'Y aunque no tenga dinero, no tenga a nadie',
  'Yo voy a seguir cantando, porque me nace',
  'Yo soy la niña de fuego',
  'Como canta Caracol, como canta Caracol',
  'Ay, esa que tú me hiciste',
  'Y una sí, pero dos no',
  'Y una sí, pero dos no',
  'Yo soy muy mía',
  'Que Dios bendiga a Pastor y Mercè',
  'A la Lil Kim, a Tego y a M.I.A.',
  'A mi familia y a la libertad',
  'Quítate, quítate, quítate tú de en medio',
  'Que tú sabes que yo te canto siete por medio',
  'Quítate, quítate, quítate tú de en medio (quite)',
  'Que tú sabes que yo te canto siete por medio',
  'Ay, que tú sabes que yo te canto siete por medio',
  'Ay, que tú sabes que yo te canto siete por medio',
  '(¡Ole!)',
];

final chikenTeriyaki = [
  'La Rosalía (uh)',
  'Rosa sin tarjeta',
  'Se las mando a tu gata',
  'Te la tengo con Roleta',
  'No hizo falta serenata',
  'Salgo y suena balacera (ey)',
  'Me visto de cualquier manera',
  'En Nueva York visitando a mi joyero',
  'Solo quiere cash, yo le doy mi dinero',
  'Pa ti naki, chicken teriyaki',
  'Tu gata quiere maki, mi gata en Kawasaki',
  'Quiero una cadena que me arruine toa la cuenta',
  'Como Naomi en los 90',
  'Rosa sin tarjeta',
  'Se las mando a tu gata (ey)',
  'Te la tengo con Roleta (ey)',
  'No hizo falta serenata',
  'Pa ti naki, chicken teriyaki',
  'Pa ti naki, chicken teriyaki',
  'Pa ti naki, chicken teriyaki',
  'Tu gata quiere maki (mi gata en Kawasaki)',
  'Quiero una cadena que me arruine toa la cuenta',
  'Como Julio en los 70 (pa ti naki, chicken teriyaki)',
  'Un billete, dos billete, una tienda de billete',
  'La más dura que le mete',
  'En Nueva York patinando pa lo Heights',
  'Toa mis domi saben la que hay, ¡eh!',
  'Y sí, la fama e una condena',
  'Pero dime otra que te pague la cena',
  'Me están tirando sombras como drag queen',
  'Chula como Mike Dean',
  'Rosa sin tarjeta',
  'Se las mando a tu gata (ey, ey)',
  'Te la tengo con Roleta',
  'No hizo falta serenata',
  'De azúcar la mami, todo sin recibo',
  'Leo pentagrama, pero no lo escribo',
  'Desde Queens hasta Tribeca',
  'Un ramo de flore azule no se seca',
  'Pa ti naki, chicken teriyaki',
  'Pa ti naki, chicken teriyaki',
  'Pa ti naki, chicken teriyaki',
  'Tu gata quiere maki, mi gata en Kawasaki',
];

final hentai = [
  'Pa, pero mírate',
  'No pienses más',
  'Na que pensar',
  'Tan rico no puede ser',
  'De cuero na',
  'Pero estoy encuera',
  'Te quiero ride',
  'Como a mi bike',
  'Hazme un tape',
  'Modo Spike',
  'Yo la batí',
  'Hasta que se montó',
  'Segundo es chingarte',
  'Lo primero e Dios',
  'So, so, so, so, so, so good',
  'Good',
  'Good',
  'So, so, so good, so, so, so good',
  'So, so, so good',
  'So good',
  'Mmm, so good',
  'Enamorá de tu pistola',
  'Roja amapola',
  'Crash, esa ola',
  'Casi me controla',
  'Enamorá de tu pistola',
  'Roja amapola',
  'Crash, esa ola',
  'Casi me controla',
  'Te quiero ride',
  'Como a mi bike',
  'Hazme un tape',
  'Modo Spike',
  'Caro como que tiene',
  'Un diamante en la punta',
  'Siempre me pone',
  'Por delante de esa puta',
  'So, so, so, so, so, so good',
  'Good',
  'Good',
  'So, so, so good',
  'So, so, so good',
  'So, so, so good',
  'So good, mmm',
  'Bebé, te quiero comer',
  'Ya',
  'Ya',
  'Ya te quiero hacer hentai',
  'Ya te quiero hacer hentai',
  'Ya te quiero hacer hentai',
  'Hacerte hentai',
  'Mmm, hentai',
];

final bizcochito = [
  'Yo no soy y ni via ser tu bizcochito',
  'Pero tengo to lo que tiene delito',
  'Que me pongan en el sol, que me derrito',
  'El mal de ojo que me manden me lo quito',
  'Yo no soy y ni via ser tu bizcochito',
  'Pero tengo to lo que tiene delito',
  'Que me pongan en el sol, que me derrito',
  'El mal de ojo que me manden me lo quito',
  'Ta-ra-rá, ta-ra-rá, ta-tá',
  'Ta-ra-ra-ta-tá-ra (me lo quito)',
  'Ta-ra-rá, ta-ra-rá, ta-tá',
  'Ta-ra-ra-ta-ta-tá-ra (que me manden me lo quito)',
  '¿Tú ere el que pimpea o te pimpean a ti?',
  'Yo elegí mi lao desde el día en que nací',
  '¿Tú ere el que pimpea o te pimpean a ti?',
  'Yo elegí mi lao desde el día en que nací',
  'Ta-ra-rá, ta-ra-rá, ta-tá',
  'Ta-ra-ra-ta-tá-ra (desde el día en que nací)',
  'Ta-ra-rá, ta-ra-rá, ta-tá',
  'Ta-ra-ra-ta-ta-tá-ra (desde el día en que nací)',
  'Desde el día en que nací',
  'Desde el día en que nací',
  'Desde el día en que nací',
  'Desde el día en que nací',
  'No basé mi carrera en tener hits',
  'Tengo hits porque yo senté las base',
  'Ya no tengo nada más que decir',
  'Pa decirlo hace falta mucha clase',
  'Y tú que estás dura te marea',
  'Hasta tu mamá lo tararea',
  'Qué más da que me tire la mala',
  'Si Haraka me tira la buena',
  'Habla bullshit, to lo que dice falsea',
  'Y mi make-up en la ola de Corea',
  'Habla bullshit, to lo que dice falsea',
  'Y mi make-up en la ola de Corea',
  'Ta-ra-rá, ta-ra-rá, ta-tá',
  'Ta-ra-ra-ta-tá-ra (en la ola de Corea)',
  'Ta-ra-rá, ta-ra-rá, ta-tá',
  'Ta-ra-ra-ta-ta-tá-ra (en la ola de Corea)',
  'Yo no soy y ni via ser tu bizcochito (ta-ra-rá, ta-ra-rá, ta-tá)',
  'Pero tengo to lo que tiene delito (Ta-ra-ra-ta-tá-ra)',
  'Que me pongan en el sol, que me derrito (ta-ra-rá, ta-ra-rá, ta-tá)',
  'El mal de ojo que me manden me lo quito (Ta-ra-ra-ta-ta-tá-ra)',
  'Ta-ra-rá, ta-ra-rá, ta-tá',
  'Ta-ra-ra-ta-tá-ra',
  'Ta-ra-rá, ta-ra-rá, ta-tá',
  'Ta-ra-ra-ta-ta-tá-ra',
];

final g3n15 = [
  '¿Me perdonarás lo que me he perdio?',
  'Son dos años ya',
  'Tú ya tienes diez',
  'Los ojos están en camino',
  'Eras de ojos cielo de ojo azul marino',
  'No sé qué te gusta',
  'Más si las carreras',
  'Naves espaciales o barcos de vela',
  'Si vives tranquilo o vives con guerra',
  'Si ya te enamoras o si antes peleas',
  'Si sientes calor',
  'Lo sientes por dentro',
  'Es que tiene un ángel',
  'Ardiendo en el pecho',
  'Si en el corazón, ya no tienes frío',
  'Es que tienes un ángel, el que yo te envió',
  'Tú siempre callao como los mayore',
  'Yo te contaré sin adorno o flores',
  'Y me toca estar donde no quiero estar',
  'Esto no es El Mal Querer, eres el mal desear',
  'Estoy en un sitio que no te llevaría',
  'Aquí nadie está en paz entre estrellas y jeringuillas',
  'Estrella de mármol, cortadas en el suelo',
  'Papelas por la calle donde pasean los modelos',
  'Hay picos en los brazos',
  'Picos en las estrellas',
  'No quiero traerte',
  'Pa que nunca vengas',
  'Pico en las estrellas',
  'Hay picos en los brazos',
  'Se amarran cuando hay frío',
  'Como yo te abrazo',
  'Bon dia, amor meu',
  'Magrada que, pensar en moments difícils',
  'Sempre ajuda moltíssim tenir una referència a Dèu',
  'Siempre es la familia primero, y',
  'No en primero, diría que en primero sempre es Dèu',
  'Y después la familia',
  'La familia es tan importante',
  'La familia siempre es importante',
  'Portas um camí que es una mica complicat',
  'Quan el miro, penso',
  'Que complicat és el món en que se ficar la Rosalía',
  'Pero bueno, si ets feliç, jo també sóc feliç',
];

final motomami = [
  'Okay, motomami',
  'Pesa mi tatami',
  'Hit a lo tsunami',
  'Oh',
  'Okay, motomami',
  'Fina, un origami',
  'Cruda a lo sashimi',
  'Oh',
  'A cada copia que ves',
  'Tú dale tu bendición',
  'Y ya no quiero competir',
  'Si no hay comparación',
  'Con la cadena hasta el pie',
  'De diabla el corazón',
  'No te crea que es sweet',
  'Tu bombón lleno de licor (prr)',
  'Okay, motomami',
  'Pesa mi tatami',
  'Hit a lo tsunami',
  'Oh',
  'Okay, motomami',
  'Fina, un origami',
  'Cruda a lo sashimi',
  'Oh',
  'Motomami, motomami, motomami',
  'Motomami, motomami, motomami',
  'Motomami, motomami, motomami',
  'Motomami, motomami, motomami',
  'Motomami, motomami, motomami',
  'Motomami, motomami, motomami',
];

final diablo = [
  'Si lo que pasó ya no pasará',
  'Si lo que pasó ya no pasará',
  'Si Dios te lo da, te lo quitará',
  'Si Dios te lo da, te lo quitará, yeh',
  'Y como tú ninguna',
  'Brillas como la luna',
  'Brillas como mis prendas',
  'Quiero que tú me entiendas',
  'La que sale por TV',
  'No es la que yo conocí',
  'No es la que yo conocí',
  'Ahora pisas Lamborghinis',
  'Y como tú ninguna',
  'Brillas como la luna',
  'Brillas como mis prendas',
  'Quiero que tú me entiendas',
  'La que sale por TV',
  'No es la que yo conocí',
  'No es la que yo conocí',
  'Yo conocí',
  'De la noche a la mañana',
  'No es que yo cambié',
  'De la noche a la mañana',
  'Mi via se me fue',
  'Y como tú ninguna (hmm)',
  'Brillas como la luna (hmm)',
  'Brillas como mis prendas (hmm)',
  'Quiero que tú me entiendas (sí)',
  'La que sale por TV (hmm)',
  'No es la que yo conocí (hmm)',
  'No es la que yo conocí (hmm)',
  'Pisas Lamborghinis',
  'Y como tú ninguna',
  'Brillas como la luna',
  'Brillas como mis prendas',
  'Quiero que tú me entiendas',
  'La que sale por TV',
  'No es la que yo conocí',
  'La amistad la rompe el diablo, diablo',
  'Guita, guita, guita por los suelos',
  'Na les importa si corren ceros',
  'Yo mi lealtad nunca la pierdo',
  'Ni por el dinero',
  'Guita, guita, guita por los suelos',
  'Na les importa si corren ceros',
  'Yo mi lealtad nunca la pierdo',
  'Ni por el dinero',
  'This must be the other side of me',
  'You are running to the light',
  'It\'s night and day',
  'It\'s night and day',
  'It\'s night and day',
  'It\'s night and day',
  'It\'s night and day',
  'It\'s night and day',
  'It\'s night and day',
  'Y como tú ninguna',
  'Brillas como la luna',
  'Brillas como mis prendas',
  'Quiero que tú me entiendas',
  'La que salía por TV',
  'No es la que yo conocí',
  'No es la que yo conocí',
  'Ahora pisas Lamborghinis',
  'La bala de Dios juega en la ruleta',
  'Tú no has vigilao, se ha ido tu pureza',
  'Ya no sé quién eres, diablo',
  'No sé ni quién eres, diablo, diablo',
];

final delirioDeGrandeza = [
  'El oro pudo más que mi dolor',
  'No tuviste compasión de mi agonía',
  'Tú sabiendo que mi alma se moría',
  'Con amigos entre copas te reías',
  'La ambición, delirio de grandeza',
  'Hizo en mí un ser martirizado',
  'Porque estaba locamente enamorado',
  'Mujer, yo no merezco esa bajeza',
  'Espero con el tiempo justiciero',
  'Que retornes buscando una ilusión de amor',
  'Y volverás a mí, así lo espero',
  'Así lo espero',
  'Mujer sin corazón',
  'Man, it\'s ridiculous',
  'I got you so delirious',
  'Kiss me through the phone',
  'While I lick you just like licorice',
  'Man, it\'s ridiculous',
  'I got you so delirious',
  'Kiss me through the phone',
  'While I lick you just like licorice',
  'Man, it\'s ridiculous',
  'I got you so delirious',
  'Kiss me through the phone',
  'While I lick you just like licorice',
  'Man, it\'s ridiculous',
  'I got you so delirious',
  'Kiss me through the phone',
  'While I lick you just like licorice',
  'Espero con el tiempo justiciero',
  'Que retornes buscando una ilusión de amor',
  'Y volverás a mí',
  'Así lo espero',
  'Así lo espero, mujer sin corazón',
];

final cuuuuuuuuuute = [
  'One, two, three, four, five, six, seven, eight, nine, ten',
  'Eleven, twelve, thirteen, fourteen, fifteen, sixteen',
  'Seventeen, eighteen, nineteen, 2021',
  'One-one-one-one',
  'One-one-one-one',
  'One-one-one-one',
  'One-one-one-one',
  'Se creen especial como un año en Miami que nieva',
  'Como una autopista sin flecha',
  'Como una utopía sin brecha',
  'Yo quiero ver la mariposa suelta (one, one)',
  'Keep it cute, manito, keep it cute',
  'Que aquí el mejor artista es Dios',
  'Keep it cute, manito, keep it cute',
  'Que aquí el mejor artista es Dios',
  'Mariposas sueltas por la calle',
  'Para verla tienes que salir',
  'Mírala, no pierda detalle',
  'Habrá quien te falle',
  'Pero yo siempre estoy ahí',
  'A de alfa, B de brava',
  'C de Charlie, angelada',
  'Crashed, Lady D',
  'Llévame lejo de aquí',
  'A de alfa, B de brava',
  'C de Charlie, angelada',
  'Crashed, Lady D',
  'Llévame lejo de aquí',
  'Keep it cute, manito, keep it cute',
  'Que aquí el mejor artista es Dios',
  'Keep it cute, manito, keep it cute',
  'Que aquí el mejor artista es Dios',
];

final comoUnG = [
  'Si no lo puedes tener, lo tendrás que soltar',
  'No estoy a tu lao, pero te deseo paz y libertad (mmh, mmh)',
  'No reces por mí, quiero que sepas que estoy bien',
  'Yo tengo mi fe, mis armas, mi cora, que aún no sé pa quién',
  'No duermo na y voy como si estuviera blindá',
  'Perdona si se me olvida que es tu cumpleaños sin más (eh-ey-ey)',
  'Tantas baladas se quedarán sin dedicar',
  'Toy triste si pienso en lo bueno que tengo que no pue durar',
  'Solo el amor con amor se paga',
  'Nada te debo y tú no me debes nada',
  'El querer que no se da, ¿dónde acaba?',
  'Si encuentro el tuyo, ya será deuda pagada',
  'Si no lo puedes tener, mejor dejarlo ir',
  'Qué pena cuando quieres algo pero Dios tiene otros planes pa ti',
  'No me enamoro de nadie, jurao, como un G',
  'Ni escribo canciones de amor, pero en esta me doblo por ti',
  'Donde me cogió la noche me perdí',
  'Los faros de los coches me llevan pallí',
  'Donde me cogió la noche me perdí',
  '(Los faros me llevan pallí)',
  'Solo el amor con amor se paga',
  'Nada te debo y tú no me debes nada',
  'El querer que no se da, ¿dónde acaba?',
  'Si encuentro el tuyo, ya será deuda pagada',
  'Guárdame, guárdame',
  'Otra vez, otra vez',
  'Mándame, mándame',
  'Ángeles, ángeles',
  'Guárdame, guárdame',
  'Otra vez, otra vez',
  'Mándame, mándame',
  'Ángeles, ángeles (jurao, como un G)',
  'Como un G de verdad',
  'Sin guardaespaldas voy por allí (jurao, como un G)',
  'Que yo mato, que yo mato, yo mato por ti',
  '(Jurao, como un G)',
  'Cantándote baladas por la madrugada',
  'Quién me lo iba a decir (jurao, como un G)',
  'Pero que dime, dime quién se atreve a decírmelo a mí',
  '(Jurao, como un G)',
  'Que siempre te querré aunque no te tenga',
  'Que siempre me tendrá aunque no me quiera',
  '(jurao, como un G)',
  'Que siempre te querré aunque no me quie-',
  'Que siempre me tendrá aunque no me quiera',
  '(jurao, como un G)',
  'Ta-ta-ta, ta-ra-ra-ra',
  'Ta-ta-ta-ta-ta-ta, ta-ra-ra-ra',
  'Ta-ta-ta-ta-ta-ta, ta-ra-ra-ra',
  'Ta-ta-ta-ta-ta-ta, ta-ra-ra-ra',
  'Ta-ta-ta-ta',
];
final abcdefg = [
  'A de alta, altura, alien',
  'B de bandida',
  'C de coqueta',
  'D de dinamita',
  'E de expensiva, emperatriz, enigma, enterada',
  'F de Flux Aeon',
  'G de guapa',
  'H de hondura',
  'I de inteligencia artificial',
  'J de jineta',
  'M de motomami, motomami, motomami',
  'Motomami, motomami',
  'N de Ni se te ocurra ni pensarlo',
  'O de orquídea',
  'P de patrona',
  'Q de qué reinona',
  'R de racineta, racineta, rango',
  'Racineta, rango',
  'S de sata',
  'T de titánica',
  'U de ultrasonidos',
  'V de vendetta',
  'W de Willy Colon',
  'De Winterfall también',
  'X de Te despejo la X en un momento',
  'Y de yenes, de yantas',
  'Y Z de zarzamora, o de zapateao, o de zorra también',
];
final laConviVersace = [
  'Juntas por la noche',
  'Puestas pal derroche',
  'Tu pelo azabache',
  'La combi Versace',
  'Juntas por la noche',
  'Puestas pal derroche',
  'Tu pelo azabache',
  'La combi Versace',
  'Que fue, que fue, que fue',
  'Vestida con colabo',
  '(Margiela colabo)',
  'Medusa arriba y abajo',
  '(Carla Bruni, wah, woh)',
  'Donatella friendzy',
  '(Kilos, kilos e tela)',
  'Soltando los benjis',
  '(Cheques, cheques)',
  'Hace party con la Fania',
  'Jangueando con salseros',
  'Bendicen toda mis canciones',
  'Para que tú te enamores',
  'Juntas por la noche',
  'Puestas pal derroche',
  'Tu pelo azabache',
  'La combi Versace',
  'Juntas por la noche',
  'Puestas pal derroche',
  'Tu pelo azabache',
  'La combi Versace',
  'Rosí season coming',
  '(Expensiva)',
  'Uzi y Albinoni',
  'Facetime con Milano',
  '(Tim Cook)',
  'Dios bendiga a Gianni',
  '(Flores para Gianni)',
  'Más fría que tu baby mama',
  'Nos fuimos 7:30',
  'Llego a la Met en pony (ah)',
  'Pa que tú te enamores',
  'Juntas por la noche',
  'Puestas pal derroche',
  'Tu pelo azabache',
  'La combi Versace',
  'Juntas por la noche',
  'Puestas pal derroche',
  'Tu pelo azabache',
  'La combi Versace',
  'Este lazo Versace saliendo del callejón',
  'Desfilamos Dior custom en el colmadón',
  'Con la tanga Gucci en una cola de motor',
  'Me llevo todo el mall montao en un camión',
  'Combino el rojo con el rosa',
  'Vestida de blanco',
  'Me visto de novia pero no soy tu esposa',
  'Las tennis Valentino',
  'Bizcocho de Moschino',
  'Gargantilla de zafiro',
  'Con diamante azul marino',
  'Y si hoy llevo la ropa fake',
  'Es porque soy la más real',
  'Bish, me creo Dapper Dan',
  'Me doy un flow de paca, me veo original',
  'Soy la marca más cara que tú no va a pode capea',
  'Juntas por la noche',
  'Puestas pal derroche',
  'Tu pelo azabache',
  'La combi Versace',
  'Juntas por la noche',
  'Puestas pal derroche',
  'Tu pelo azabache',
  'La combi Versace',
  'Fue el roman-, fue el roman-',
  'Colale , fue el roman-, hmmm',
  'Se me ve el culo en Versace',
  'Fue-fuera del bajo mundo, fuera',
  'Colale, cola-, colale, mmm, mmm, mmm',
  'Fuera, fuera, fuera',
  'Fuera, fuera, fuera',
  'Ah, ah',
  'Se me ve el culo en Versace',
  'Se me ve el culo en Versace',
  'Del bajo mun-, del bajo mun-, yeh',
  'Del bajo mun-, yeh',
  'Mmm, ah, ah, mmm, cheque',
];

final sakura = [
  'Las flores de esta ciudad no huelen a na',
  '¿Por qué será? ¿Por qué será?',
  'Y toa las chicas son tan bonitas, tan plásticas',
  '¿Por qué será? ¿Por qué será?',
  'Flor de sakura',
  'Flor de sakura',
  'Ser una popstar nunca te dura',
  'Flor de sakura',
  'Flor de sakura',
  'No me da pena, me da ternura',
  'No pa siempre pues ser una estrella y brillar',
  'Vya reírme cuando tenga 80 y mire patrás',
  'Nunca me ha dao miedo la risa de un loco',
  'Más miedo me da el que miente o el que ríe poco',
  'Si tienes 60 y te endiablas cuando una mujer frontea',
  'Es que no has aprendío na o es que tienes un problema',
  'Flor de sakura',
  'Flor de sakura',
  'Ser una popstar nunca te dura',
  'Flor de sakura',
  'Flor de sakura',
  'No me da pena, me da ternura',
  'La que sabe, sabe',
  'Que si estoy en esto es para romper',
  'Y si me rompo con esto, pues me romperé',
  '¿Y qué?',
  'Solo hay riesgo si hay algo que perder',
  'Las llamas son bonitas porque no tienen orden',
  'Y el fuego es bonito porque todo lo rompe',
];
